###
POST http://localhost:3006/api/phonebill HTTP/1.1
Content-type: application/json

{
    "price_plan": "sms 101",
    "actions" : "call, sms, call"
}


###
GET http://localhost:3006/api/price_plans HTTP/1.1


###
POST http://localhost:3006/api/price_plan/create HTTP/1.1
Content-type: application/json

{
    "name": "call 201",
  "call_cost" : 2.3,
   "sms_cost": 0.93
}
    

###
POST http://localhost:3006/api/price_plan/update HTTP/1.1
Content-type: application/json

{
    "name": "sms 101",
   "call_cost" : 2.65,
   " sms_cost": 0.45
}


###
POST http://localhost:3006/api/price_plan/delete HTTP/1.1
Content-type: application/json

{
   " id": 17
}